### ISSUE TITLE
SyntaxError: Unexpected Token

### ISSUE THREAD

**Issue by AmenRa666** [noahDess/corenlp-js-prefab#2]
Hello, i got this error when i try to launch your test:

```
undefined:1
{"sentences":[{"index":0,"parse":"(ROOT


SyntaxError: Unexpected token
 in JSON at position 39
    at Object.parse (native)
    at Object.process (/Users/elias/wikipedia-article-analyzer/node_modules/corenlp-js-prefab/index.js:14:17)
    at Object.<anonymous> (/Users/elias/wikipedia-article-analyzer/node_modules/corenlp-js-prefab/example.js:4:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

Can't understand why, I'm on macOS and I've installed _wget_ with Brew.
Ideas?

**Comment by unhandyandy** [comment]
I get the same error when I apply JSON.parse to the output of corenlp.

**Comment by thomwolf** [comment]
I have the same problem, did you find a solution ?

**Comment by noahDess** [comment]
I am sorry I am no long able to maintain this
